---
name: gomod-go-version-updater-action
description: gomod-go-version-updater-action
inputs:
  workflow_file:
    default: golang.yml
    description: |
      The description of the GitHub project.
    required: true
runs:
  using: 'composite'
  steps:
    - name: display the gh cli version
      run: gh --version
      shell: bash
    - uses: actions/checkout@v4.1.3
      with:
        ref: main
    - name: set branch name
      run: |
        echo "GOMOD_GO_VERSION_UPDATER_LABEL=gomod-go-version-updater" >> $GITHUB_ENV
        echo "GOMOD_GO_VERSION_UPDATER_ACTION_BRANCH=update-go-version-in-go-mod-file" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9.18
    - name: Install dependencies
      run: |
        pip install pytest pytest-cov requests
      shell: bash
    - name: Create label
      run: |
        gh label create ${GOMOD_GO_VERSION_UPDATER_LABEL} --color "#F50BAB" --description "Pull requests that update Go version in the go.mod file" --force
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
    - name: update go version and push branch
      run: |
        git fetch -p -P
        git checkout -b ${GOMOD_GO_VERSION_UPDATER_ACTION_BRANCH}

        python --version
        python3 --version

        export GOMOD_GO_VERSION_UPDATER_ACTION_OUTPUT=$(python ${{ github.action_path }}/main.py 2>&1 | sed "s|.*\(bump.*\)|\1|")
        echo "GOMOD_GO_VERSION_UPDATER_ACTION_OUTPUT: ${GOMOD_GO_VERSION_UPDATER_ACTION_OUTPUT}"

        export GOMOD_GO_VERSION_UPDATER_ACTION_MESSAGE="build(deps): ${GOMOD_GO_VERSION_UPDATER_ACTION_OUTPUT}"
        echo "GOMOD_GO_VERSION_UPDATER_ACTION_MESSAGE: ${GOMOD_GO_VERSION_UPDATER_ACTION_MESSAGE}"

        if [ -n "$(git status --porcelain)" ]; then echo "There are uncommitted changes."; else echo "No changes to commit." && exit 0; fi

        echo "git add..."
        git add go.mod

        echo "git config user..."
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com

        echo "git commit..."
        if ! git commit -m "${GOMOD_GO_VERSION_UPDATER_ACTION_MESSAGE}"; then git commit --amend --no-edit; fi

        echo "git push..."
        git push origin ${GOMOD_GO_VERSION_UPDATER_ACTION_BRANCH} -f

        if gh pr list --json title | jq -e '.[] | select(.title | test("build\\(deps\\): bump golang version in go\\.mod file from .* to .*"))'; then
          echo "pr exists already"
          exit 0
        fi

        echo "create pr..."
        gh pr create \
          --base main \
          --head "${GOMOD_GO_VERSION_UPDATER_ACTION_BRANCH}" \
          --fill \
          --label dependencies \
          --label go \
          --label ${GOMOD_GO_VERSION_UPDATER_LABEL}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
    - uses: actions/setup-go@v5.0.1
      with:
        go-version-file: 'go.mod'
        cache: false
    - name: go mod tidy
      run: |
        go mod tidy
      shell: bash
    - name: commit and force push if needed
      run: |
        if [ -n "$(git status --porcelain)" ]; then echo "There are uncommitted changes."; else echo "No changes to commit." && exit 0; fi

        git add .
        git commit --amend --no-edit
        git push origin ${GOMOD_GO_VERSION_UPDATER_ACTION_BRANCH} -f
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
